services:
  web:
    build:
      context: .
      args:
        TARGET_PLATFORM: ${TARGET_PLATFORM:-linux/amd64}
    container_name: fastyshop-backend
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    depends_on:
      - db
      - redis
    env_file:
      - .env.production
    environment:
      RAILS_ENV: production
    restart: always
    # no ports exposed, handled by nginx

  db:
    image: postgres:17
    container_name: fastyshop-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: redis:7.4
    container_name: fastyshop-redis
    restart: always
    # НЕ открывай порты наружу!
    # ports: []

volumes:
  postgres_data:
