services:
  web-test:
    build:
      context: .
      args:
        TARGET_PLATFORM: ${TARGET_PLATFORM:-linux/arm64}
    container_name: kagi-backend-test
    command: [ "sleep", "infinity" ]
    env_file:
      - .env.test
    environment:
      RAILS_ENV: test
    depends_on:
      - db
      - redis
  # 📦 Rails-приложение (API-only backend)
  web:
    # В development окружении монтируем локальную папку внутрь контейнера
    # Это позволяет видеть все изменения в коде в реальном времени (hot reload)
    volumes:
      - .:/app
      - /app/vendor

    # Прокидываем порт 3000 наружу, чтобы приложение было доступно по http://localhost:3000
    ports:
      - "3000:3000"

  redis:
    ports:
      - "6379:6379"

  db:
    # Открываем порт PostgreSQL для подключения снаружи (например, через Postico)
    ports:
      - "5432:5432"
