name: 🐞 Bug report
description: Сообщи об ошибке в kagi-backend
title: "[BUG] <краткое описание>"
labels: [bug]
assignees:
  - rubyhat

body:
  - type: markdown
    attributes:
      value: |
        Спасибо, что сообщаешь о баге! Пожалуйста, заполни как можно подробнее 👇

  - type: textarea
    id: description
    attributes:
      label: 📋 Описание бага
      description: Расскажи, что произошло. Что пошло не так?
      placeholder: Опиши поведение, включая все детали
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 🧪 Шаги для воспроизведения
      description: Перечисли шаги, которые приводят к багу
      placeholder: |
        1. Зайти под пользователем seller
        2. Открыть /shops/new
        3. Нажать "Сохранить" без выбора юридического профиля
        4. Получить ошибку
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ Ожидаемое поведение
      description: Как должно работать в идеале?

  - type: textarea
    id: actual
    attributes:
      label: ❌ Фактическое поведение
      description: Что происходит на самом деле?

  - type: textarea
    id: logs
    attributes:
      label: 🐛 Скриншоты или логи
      description: Приложи, если есть (stacktrace, curl, json и т.п.)

  - type: dropdown
    id: severity
    attributes:
      label: 🔥 Уровень критичности
      description: Насколько баг критичен?
      options:
        - Blocker — мешает разработке / релизу
        - Critical — ломает основной функционал
        - Medium — влияет на UX, но можно работать
        - Low — минорный баг, можно отложить

  - type: checkboxes
    id: areas
    attributes:
      label: 📦 Относится к компонентам
      description: Какие части системы затронуты?
      options:
        - label: Backend (Rails API)
        - label: PostgreSQL / Redis
        - label: DevOps / Docker
        - label: Общая архитектура / инфраструктура
