name: ✨ Feature request
description: Предложи новую фичу для проекта
title: "[FEATURE] <краткое описание>"
labels: [feature]
assignees:
  - rubyhat

body:
  - type: markdown
    attributes:
      value: |
        Спасибо, что предлагаешь улучшение! Чем больше деталей — тем лучше 👇

  - type: textarea
    id: problem
    attributes:
      label: 💡 Проблема или возможность
      description: Какую проблему ты хочешь решить или какую возможность добавить?
      placeholder: "Например: продавец не может отслеживать выручку за месяц"

  - type: textarea
    id: proposal
    attributes:
      label: 🛠️ Предложенное решение
      description: Как ты предлагаешь это реализовать?
      placeholder: Добавить API `/store_stats` с фильтрацией по дате

  - type: textarea
    id: alternative
    attributes:
      label: 🔄 Альтернативные подходы
      description: Были ли у тебя другие идеи?

  - type: dropdown
    id: importance
    attributes:
      label: 📊 Приоритет
      options:
        - High — критично
        - Medium — желательно, но можно позже
        - Low — nice-to-have
