name: 🧹 Tech debt / Refactor
description: Опиши технический долг или необходимость рефакторинга
title: "[REFACTOR] <краткое описание>"
labels: [tech-debt, refactor]
assignees:
  - rubyhat

body:
  - type: markdown
    attributes:
      value: |
        Долг сегодня = баги завтра. Опиши, что нужно починить или улучшить 👇

  - type: textarea
    id: context
    attributes:
      label: 📎 Контекст
      description: Где и почему возникла проблема?
      placeholder: "Например: `ProductCategoryController#index` стал слишком сложным"

  - type: textarea
    id: problem
    attributes:
      label: 🐢 Проблема
      description: Что делает текущую реализацию неэффективной или опасной?
      placeholder: Много логики в контроллере, отсутствие тестов, дублирование

  - type: textarea
    id: suggestion
    attributes:
      label: 🔧 Что предлагается сделать?
      placeholder: Вынести фильтрацию в сервис + покрыть тестами

  - type: dropdown
    id: impact
    attributes:
      label: 🎯 Влияние
      options:
        - High — влияет на стабильность / безопасность
        - Medium — влияет на читаемость / поддержку
        - Low — косметика или потенциальная проблема
