---
openapi: 3.0.1
info:
  title: Kagi Backend API
  version: v1
components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
- Bearer: []
paths:
  "/api/v1/auth/login":
    post:
      summary: Аутентификация пользователя
      tags:
      - Auth
      parameters: []
      responses:
        '200':
          description: Успешный вход
        '401':
          description: Пользователь не найден
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  type: string
                  example: "+77001234567"
                password:
                  type: string
                  example: SecurePass123!
              required:
              - phone
              - password
